import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Navbar, Footer } from "@/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Oshodi Foods",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
